[package]
name = "webcfg"
version = "0.1.0"
edition = "2024"

[dependencies]
ammonia = "4.1.2"
anyhow = { version = "1.0.102", features = [] }
axum = { version = "0.8.9", features = ["tokio", "json", "http2"] }
camino = { version = "1.2.2", features = [] }
jsonwebtoken = { version = "10.4.0", features = [] }
openid = { version = "0.23.0", features = ["http2", "native-tls"] }
reqwest = "0.13.4"
scraper = { version = "0.27.0", features = ["default", "serde"] }
serde = { version = "1.0.228", features = ["default", "derive"] }
thiserror = { version = "2.0.18", features = [] }
tokio = { version = "1.52.3", features = ["sync", "time", "net", "macros", "fs", "rt-multi-thread"]}
toml = { version = "1.1.2", features = ["default"] }
#tower-http = { version = "0.6.11", features = ["full"]}

[lints]
workspace = true
